import Head from "next/head";
import { Inter } from "@next/font/google";
import Inicio from "@/components/Inicio";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ articles }) {
  return (
    <>
      <Head>
        <title>Home📰||News-App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Inicio articles={articles} />
    </>
  );
}
export async function getServerSideProps(context) {
  const response = await fetch(
    "https://newsapi.org/v2/top-headlines?country=us&category=business&apiKey=33f2ae96cb644d90aa1b9cef04880a42"
  );

  const { articles } = await response.json();
  return {
    props: {
      articles: articles,
    },
  };
}
